/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MK64FN1M0xxx12
package_id: MK64FN1M0VLL12
mcu_data: ksdk2_0
processor_version: 7.0.1
board: FRDM-K64F
pin_labels:
- {pin_num: '57', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20, label: LED6_G, identifier: LED6_G}
- {pin_num: '35', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, label: INPUT_ADC, identifier: INPUT_ADC}
- {pin_num: '69', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, label: LED7_R, identifier: LED7_R}
- {pin_num: '36', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, label: IR_OUT, identifier: IR_OUT}
- {pin_num: '72', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, label: LED7_B, identifier: LED7_B}
- {pin_num: '73', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: LED8_R, identifier: LED8_R}
- {pin_num: '64', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, label: LED3_G, identifier: LED3_R;LED3_G}
- {pin_num: '65', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, label: LED3_B, identifier: LED3_B}
- {pin_num: '71', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, label: LED4_R, identifier: LED4_R}
- {pin_num: '80', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, label: LED4_G, identifier: LED4_G}
- {pin_num: '81', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, label: LED4_B, identifier: LED4_B}
- {pin_num: '77', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, label: LED5_B, identifier: INPUT_ADC;LED5_B}
- {pin_num: '79', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FB_AD8, label: LED5_G, identifier: CMP0_IN1;SAIDA;LED5_G}
- {pin_num: '70', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, label: LED5_R, identifier: LED5_R}
- {pin_num: '84', pin_signal: PTC12/UART4_RTS_b/FB_AD27/FTM3_FLT0, label: LED8_G, identifier: LED8_G}
- {pin_num: '76', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, label: LED8_B, identifier: LED8_B}
- {pin_num: '93', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: LED9_R, identifier: LED9_R}
- {pin_num: '95', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL, label: LED9_G, identifier: UART2_RX;LED9_G}
- {pin_num: '96', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, label: LED9_B, identifier: UART2_TX;LED9_B}
- {pin_num: '94', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: LED10_R, identifier: LED10_R}
- {pin_num: '32', pin_signal: ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN, label: LED10_G, identifier: ACCEL_SDA;LED10_G}
- {pin_num: '31', pin_signal: ADC0_SE17/PTE24/UART4_TX/I2C0_SCL/EWM_OUT_b, label: LED10_B, identifier: ACCEL_SCL;LED10_B}
- {pin_num: '33', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, label: LED6_R, identifier: LED_GREEN;LED6_R}
- {pin_num: '66', pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, label: LED3_R, identifier: RF_WIFI_CE;LED3_R}
- {pin_num: '55', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, label: LED1_R, identifier: ADC0_SE12;LED1_R}
- {pin_num: '56', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, label: LED1_G, identifier: LED1_G}
- {pin_num: '58', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, label: LED1_B, identifier: LED1_B}
- {pin_num: '59', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, label: LED2_R, identifier: LED2_R}
- {pin_num: '83', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, label: LED2_G, identifier: LED2_G}
- {pin_num: '82', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: LED2_B, identifier: LED2_B}
- {pin_num: '98', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, label: LED7_G, identifier: WIFI_SCK;LED7_G}
- {pin_num: '100', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, label: LED6_B, identifier: WIFI_MISO;LED6_B}
- {pin_num: '87', pin_signal: PTC15/UART4_TX/FB_AD24, label: INPUT_ADC, identifier: INPUT_ADC}
- {pin_num: '34', pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/JTAG_TCLK/SWD_CLK/EZP_CLK, label: LED3_R, identifier: LED3_R}
- {pin_num: '68', pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, label: LED_RED, identifier: LED_RED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '62', peripheral: UART0, signal: RX, pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN}
  - {pin_num: '63', peripheral: UART0, signal: TX, pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b}
  - {pin_num: '90', peripheral: ENET, signal: 'TMR_1588, 0', pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b}
  - {pin_num: '91', peripheral: ENET, signal: 'TMR_1588, 1', pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b}
  - {pin_num: '92', peripheral: ENET, signal: 'TMR_1588, 2', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b}
  - {pin_num: '54', peripheral: ENET, signal: RMII_MDC, pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB}
  - {pin_num: '53', peripheral: ENET, signal: RMII_MDIO, pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA, slew_rate: fast,
    open_drain: enable, drive_strength: low, pull_select: up, pull_enable: enable, passive_filter: disable}
  - {pin_num: '42', peripheral: ENET, signal: RMII_RXD1, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA}
  - {pin_num: '43', peripheral: ENET, signal: RMII_RXD0, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB}
  - {pin_num: '44', peripheral: ENET, signal: RMII_CRS_DV, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1}
  - {pin_num: '45', peripheral: ENET, signal: RMII_TXEN, pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0}
  - {pin_num: '47', peripheral: ENET, signal: RMII_TXD1, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK}
  - {pin_num: '46', peripheral: ENET, signal: RMII_TXD0, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1}
  - {pin_num: '39', peripheral: ENET, signal: RMII_RXER, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
  - {pin_num: '68', peripheral: GPIOB, signal: 'GPIO, 22', pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, direction: OUTPUT, drive_strength: high}
  - {pin_num: '55', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, identifier: LED1_R, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '56', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '58', peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, direction: OUTPUT, drive_strength: high}
  - {pin_num: '59', peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, direction: OUTPUT, drive_strength: high}
  - {pin_num: '83', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, direction: OUTPUT, drive_strength: high}
  - {pin_num: '82', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, direction: OUTPUT, drive_strength: high}
  - {pin_num: '64', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, identifier: LED3_G, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '65', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, direction: OUTPUT, drive_strength: high}
  - {pin_num: '71', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '80', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, direction: OUTPUT, drive_strength: high}
  - {pin_num: '81', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, direction: OUTPUT, drive_strength: high}
  - {pin_num: '70', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, direction: OUTPUT, drive_strength: high}
  - {pin_num: '79', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FB_AD8, identifier: LED5_G, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '77', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, identifier: LED5_B, direction: OUTPUT,
    drive_strength: high, pull_enable: enable}
  - {pin_num: '33', peripheral: GPIOE, signal: 'GPIO, 26', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, identifier: LED6_R, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '57', peripheral: GPIOB, signal: 'GPIO, 9', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20, direction: OUTPUT, drive_strength: high}
  - {pin_num: '100', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, identifier: LED6_B, direction: OUTPUT, drive_strength: high}
  - {pin_num: '69', peripheral: GPIOB, signal: 'GPIO, 23', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, direction: OUTPUT, drive_strength: high}
  - {pin_num: '98', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, identifier: LED7_G,
    direction: OUTPUT, drive_strength: high}
  - {pin_num: '72', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '73', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, direction: OUTPUT, drive_strength: high}
  - {pin_num: '84', peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/UART4_RTS_b/FB_AD27/FTM3_FLT0, direction: OUTPUT, drive_strength: high, pull_select: up,
    pull_enable: disable}
  - {pin_num: '76', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, direction: OUTPUT, drive_strength: high}
  - {pin_num: '93', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: OUTPUT, drive_strength: high}
  - {pin_num: '95', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL, identifier: LED9_G, direction: OUTPUT,
    drive_strength: high}
  - {pin_num: '96', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, identifier: LED9_B, direction: OUTPUT, drive_strength: high}
  - {pin_num: '94', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: OUTPUT, drive_strength: high}
  - {pin_num: '32', peripheral: GPIOE, signal: 'GPIO, 25', pin_signal: ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN, identifier: LED10_G, direction: OUTPUT, drive_strength: high}
  - {pin_num: '31', peripheral: GPIOE, signal: 'GPIO, 24', pin_signal: ADC0_SE17/PTE24/UART4_TX/I2C0_SCL/EWM_OUT_b, identifier: LED10_B, direction: OUTPUT, drive_strength: high}
  - {pin_num: '35', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge,
    drive_strength: low, pull_select: down}
  - {pin_num: '36', peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, direction: OUTPUT, pull_enable: disable}
  - {pin_num: '66', peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, identifier: LED3_R, direction: OUTPUT, drive_strength: high,
    pull_select: up, pull_enable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t INPUT_ADC_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_INPUT_ADC_GPIO, BOARD_INITPINS_INPUT_ADC_PIN, &INPUT_ADC_config);

    gpio_pin_config_t IR_OUT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA2 (pin 36)  */
    GPIO_PinInit(BOARD_INITPINS_IR_OUT_GPIO, BOARD_INITPINS_IR_OUT_PIN, &IR_OUT_config);

    gpio_pin_config_t LED1_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_R_GPIO, BOARD_INITPINS_LED1_R_PIN, &LED1_R_config);

    gpio_pin_config_t LED1_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 56)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_G_GPIO, BOARD_INITPINS_LED1_G_PIN, &LED1_G_config);

    gpio_pin_config_t LED6_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_LED6_G_GPIO, BOARD_INITPINS_LED6_G_PIN, &LED6_G_config);

    gpio_pin_config_t LED1_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB10 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_B_GPIO, BOARD_INITPINS_LED1_B_PIN, &LED1_B_config);

    gpio_pin_config_t LED2_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB11 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_LED2_R_GPIO, BOARD_INITPINS_LED2_R_PIN, &LED2_R_config);

    gpio_pin_config_t LED3_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_LED3_G_GPIO, BOARD_INITPINS_LED3_G_PIN, &LED3_G_config);

    gpio_pin_config_t LED3_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 65)  */
    GPIO_PinInit(BOARD_INITPINS_LED3_B_GPIO, BOARD_INITPINS_LED3_B_PIN, &LED3_B_config);

    gpio_pin_config_t LED3_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin 66)  */
    GPIO_PinInit(BOARD_INITPINS_LED3_R_GPIO, BOARD_INITPINS_LED3_R_PIN, &LED3_R_config);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB22 (pin 68)  */
    GPIO_PinInit(BOARD_INITPINS_LED_RED_GPIO, BOARD_INITPINS_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED7_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB23 (pin 69)  */
    GPIO_PinInit(BOARD_INITPINS_LED7_R_GPIO, BOARD_INITPINS_LED7_R_PIN, &LED7_R_config);

    gpio_pin_config_t LED5_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 70)  */
    GPIO_PinInit(BOARD_INITPINS_LED5_R_GPIO, BOARD_INITPINS_LED5_R_PIN, &LED5_R_config);

    gpio_pin_config_t LED4_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 71)  */
    GPIO_PinInit(BOARD_INITPINS_LED4_R_GPIO, BOARD_INITPINS_LED4_R_PIN, &LED4_R_config);

    gpio_pin_config_t LED7_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 72)  */
    GPIO_PinInit(BOARD_INITPINS_LED7_B_GPIO, BOARD_INITPINS_LED7_B_PIN, &LED7_B_config);

    gpio_pin_config_t LED8_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 73)  */
    GPIO_PinInit(BOARD_INITPINS_LED8_R_GPIO, BOARD_INITPINS_LED8_R_PIN, &LED8_R_config);

    gpio_pin_config_t LED8_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 76)  */
    GPIO_PinInit(BOARD_INITPINS_LED8_B_GPIO, BOARD_INITPINS_LED8_B_PIN, &LED8_B_config);

    gpio_pin_config_t LED5_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 77)  */
    GPIO_PinInit(BOARD_INITPINS_LED5_B_GPIO, BOARD_INITPINS_LED5_B_PIN, &LED5_B_config);

    gpio_pin_config_t LED5_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC7 (pin 79)  */
    GPIO_PinInit(BOARD_INITPINS_LED5_G_GPIO, BOARD_INITPINS_LED5_G_PIN, &LED5_G_config);

    gpio_pin_config_t LED4_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin 80)  */
    GPIO_PinInit(BOARD_INITPINS_LED4_G_GPIO, BOARD_INITPINS_LED4_G_PIN, &LED4_G_config);

    gpio_pin_config_t LED4_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 81)  */
    GPIO_PinInit(BOARD_INITPINS_LED4_B_GPIO, BOARD_INITPINS_LED4_B_PIN, &LED4_B_config);

    gpio_pin_config_t LED2_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin 82)  */
    GPIO_PinInit(BOARD_INITPINS_LED2_B_GPIO, BOARD_INITPINS_LED2_B_PIN, &LED2_B_config);

    gpio_pin_config_t LED2_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin 83)  */
    GPIO_PinInit(BOARD_INITPINS_LED2_G_GPIO, BOARD_INITPINS_LED2_G_PIN, &LED2_G_config);

    gpio_pin_config_t LED8_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC12 (pin 84)  */
    GPIO_PinInit(BOARD_INITPINS_LED8_G_GPIO, BOARD_INITPINS_LED8_G_PIN, &LED8_G_config);

    gpio_pin_config_t LED9_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin 93)  */
    GPIO_PinInit(BOARD_INITPINS_LED9_R_GPIO, BOARD_INITPINS_LED9_R_PIN, &LED9_R_config);

    gpio_pin_config_t LED10_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 94)  */
    GPIO_PinInit(BOARD_INITPINS_LED10_R_GPIO, BOARD_INITPINS_LED10_R_PIN, &LED10_R_config);

    gpio_pin_config_t LED9_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin 95)  */
    GPIO_PinInit(BOARD_INITPINS_LED9_G_GPIO, BOARD_INITPINS_LED9_G_PIN, &LED9_G_config);

    gpio_pin_config_t LED9_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 96)  */
    GPIO_PinInit(BOARD_INITPINS_LED9_B_GPIO, BOARD_INITPINS_LED9_B_PIN, &LED9_B_config);

    gpio_pin_config_t LED7_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 98)  */
    GPIO_PinInit(BOARD_INITPINS_LED7_G_GPIO, BOARD_INITPINS_LED7_G_PIN, &LED7_G_config);

    gpio_pin_config_t LED6_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 100)  */
    GPIO_PinInit(BOARD_INITPINS_LED6_B_GPIO, BOARD_INITPINS_LED6_B_PIN, &LED6_B_config);

    gpio_pin_config_t LED10_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE24 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_LED10_B_GPIO, BOARD_INITPINS_LED10_B_PIN, &LED10_B_config);

    gpio_pin_config_t LED10_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE25 (pin 32)  */
    GPIO_PinInit(BOARD_INITPINS_LED10_G_GPIO, BOARD_INITPINS_LED10_G_PIN, &LED10_G_config);

    gpio_pin_config_t LED6_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE26 (pin 33)  */
    GPIO_PinInit(BOARD_INITPINS_LED6_R_GPIO, BOARD_INITPINS_LED6_R_PIN, &LED6_R_config);

    /* PORTA1 (pin 35) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_INPUT_ADC_PORT, BOARD_INITPINS_INPUT_ADC_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA1 (pin 35): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_INPUT_ADC_PORT, BOARD_INITPINS_INPUT_ADC_PIN, kPORT_InterruptRisingEdge);

    PORTA->PCR[1] = ((PORTA->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_LowDriveStrength)

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown));

    /* PORTA12 (pin 42) is configured as RMII0_RXD1 */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_RXD1_PORT, BOARD_INITPINS_RMII0_RXD1_PIN, kPORT_MuxAlt4);

    /* PORTA13 (pin 43) is configured as RMII0_RXD0 */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_RXD0_PORT, BOARD_INITPINS_RMII0_RXD0_PIN, kPORT_MuxAlt4);

    /* PORTA14 (pin 44) is configured as RMII0_CRS_DV */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_CRS_DV_PORT, BOARD_INITPINS_RMII0_CRS_DV_PIN, kPORT_MuxAlt4);

    /* PORTA15 (pin 45) is configured as RMII0_TXEN */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_TXEN_PORT, BOARD_INITPINS_RMII0_TXEN_PIN, kPORT_MuxAlt4);

    /* PORTA16 (pin 46) is configured as RMII0_TXD0 */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_TXD0_PORT, BOARD_INITPINS_RMII0_TXD0_PIN, kPORT_MuxAlt4);

    /* PORTA17 (pin 47) is configured as RMII0_TXD1 */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_TXD1_PORT, BOARD_INITPINS_RMII0_TXD1_PIN, kPORT_MuxAlt4);

    /* PORTA2 (pin 36) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_IR_OUT_PORT, BOARD_INITPINS_IR_OUT_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[2] = ((PORTA->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA5 (pin 39) is configured as RMII0_RXER */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_RXER_PORT, BOARD_INITPINS_RMII0_RXER_PIN, kPORT_MuxAlt4);

    const port_pin_config_t RMII0_MDIO = {/* Internal pull-up resistor is enabled */
                                          kPORT_PullUp,
                                          /* Fast slew rate is configured */
                                          kPORT_FastSlewRate,
                                          /* Passive filter is disabled */
                                          kPORT_PassiveFilterDisable,
                                          /* Open drain is enabled */
                                          kPORT_OpenDrainEnable,
                                          /* Low drive strength is configured */
                                          kPORT_LowDriveStrength,
                                          /* Pin is configured as RMII0_MDIO */
                                          kPORT_MuxAlt4,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          kPORT_UnlockRegister};
    /* PORTB0 (pin 53) is configured as RMII0_MDIO */
    PORT_SetPinConfig(BOARD_INITPINS_RMII0_MDIO_PORT, BOARD_INITPINS_RMII0_MDIO_PIN, &RMII0_MDIO);

    /* PORTB1 (pin 54) is configured as RMII0_MDC */
    PORT_SetPinMux(BOARD_INITPINS_RMII0_MDC_PORT, BOARD_INITPINS_RMII0_MDC_PIN, kPORT_MuxAlt4);

    /* PORTB10 (pin 58) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_LED1_B_PORT, BOARD_INITPINS_LED1_B_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[10] = ((PORTB->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB11 (pin 59) is configured as PTB11 */
    PORT_SetPinMux(BOARD_INITPINS_LED2_R_PORT, BOARD_INITPINS_LED2_R_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[11] = ((PORTB->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB16 (pin 62) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_RX_PORT, BOARD_INITPINS_DEBUG_UART_RX_PIN, kPORT_MuxAlt3);

    /* PORTB17 (pin 63) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_TX_PORT, BOARD_INITPINS_DEBUG_UART_TX_PIN, kPORT_MuxAlt3);

    /* PORTB18 (pin 64) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_LED3_G_PORT, BOARD_INITPINS_LED3_G_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[18] = ((PORTB->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB19 (pin 65) is configured as PTB19 */
    PORT_SetPinMux(BOARD_INITPINS_LED3_B_PORT, BOARD_INITPINS_LED3_B_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[19] = ((PORTB->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB2 (pin 55) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_LED1_R_PORT, BOARD_INITPINS_LED1_R_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[2] = ((PORTB->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB20 (pin 66) is configured as PTB20 */
    PORT_SetPinMux(BOARD_INITPINS_LED3_R_PORT, BOARD_INITPINS_LED3_R_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[20] = ((PORTB->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp)

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB22 (pin 68) is configured as PTB22 */
    PORT_SetPinMux(BOARD_INITPINS_LED_RED_PORT, BOARD_INITPINS_LED_RED_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[22] = ((PORTB->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB23 (pin 69) is configured as PTB23 */
    PORT_SetPinMux(BOARD_INITPINS_LED7_R_PORT, BOARD_INITPINS_LED7_R_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[23] = ((PORTB->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB3 (pin 56) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_LED1_G_PORT, BOARD_INITPINS_LED1_G_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[3] = ((PORTB->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB9 (pin 57) is configured as PTB9 */
    PORT_SetPinMux(BOARD_INITPINS_LED6_G_PORT, BOARD_INITPINS_LED6_G_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[9] = ((PORTB->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC0 (pin 70) is configured as PTC0 */
    PORT_SetPinMux(BOARD_INITPINS_LED5_R_PORT, BOARD_INITPINS_LED5_R_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[0] = ((PORTC->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC1 (pin 71) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_LED4_R_PORT, BOARD_INITPINS_LED4_R_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC10 (pin 82) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_LED2_B_PORT, BOARD_INITPINS_LED2_B_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[10] = ((PORTC->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC11 (pin 83) is configured as PTC11 */
    PORT_SetPinMux(BOARD_INITPINS_LED2_G_PORT, BOARD_INITPINS_LED2_G_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[11] = ((PORTC->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC12 (pin 84) is configured as PTC12 */
    PORT_SetPinMux(BOARD_INITPINS_LED8_G_PORT, BOARD_INITPINS_LED8_G_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[12] = ((PORTC->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp)

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC16 (pin 90) is configured as ENET0_1588_TMR0 */
    PORT_SetPinMux(BOARD_INITPINS_TMR_1588_0_PORT, BOARD_INITPINS_TMR_1588_0_PIN, kPORT_MuxAlt4);

    /* PORTC17 (pin 91) is configured as ENET0_1588_TMR1 */
    PORT_SetPinMux(BOARD_INITPINS_TMR_1588_1_PORT, BOARD_INITPINS_TMR_1588_1_PIN, kPORT_MuxAlt4);

    /* PORTC18 (pin 92) is configured as ENET0_1588_TMR2 */
    PORT_SetPinMux(PORTC, 18U, kPORT_MuxAlt4);

    /* PORTC2 (pin 72) is configured as PTC2 */
    PORT_SetPinMux(BOARD_INITPINS_LED7_B_PORT, BOARD_INITPINS_LED7_B_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[2] = ((PORTC->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC3 (pin 73) is configured as PTC3 */
    PORT_SetPinMux(BOARD_INITPINS_LED8_R_PORT, BOARD_INITPINS_LED8_R_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[3] = ((PORTC->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC4 (pin 76) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_LED8_B_PORT, BOARD_INITPINS_LED8_B_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[4] = ((PORTC->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC5 (pin 77) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_LED5_B_PORT, BOARD_INITPINS_LED5_B_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[5] = ((PORTC->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is enabled on the corresponding pin. */
                     | (uint32_t)(PORT_PCR_PE_MASK)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC7 (pin 79) is configured as PTC7 */
    PORT_SetPinMux(BOARD_INITPINS_LED5_G_PORT, BOARD_INITPINS_LED5_G_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[7] = ((PORTC->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC8 (pin 80) is configured as PTC8 */
    PORT_SetPinMux(BOARD_INITPINS_LED4_G_PORT, BOARD_INITPINS_LED4_G_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[8] = ((PORTC->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC9 (pin 81) is configured as PTC9 */
    PORT_SetPinMux(BOARD_INITPINS_LED4_B_PORT, BOARD_INITPINS_LED4_B_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[9] = ((PORTC->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD0 (pin 93) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_LED9_R_PORT, BOARD_INITPINS_LED9_R_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[0] = ((PORTD->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD1 (pin 94) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_LED10_R_PORT, BOARD_INITPINS_LED10_R_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[1] = ((PORTD->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD2 (pin 95) is configured as PTD2 */
    PORT_SetPinMux(BOARD_INITPINS_LED9_G_PORT, BOARD_INITPINS_LED9_G_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[2] = ((PORTD->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD3 (pin 96) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_LED9_B_PORT, BOARD_INITPINS_LED9_B_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[3] = ((PORTD->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD5 (pin 98) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_LED7_G_PORT, BOARD_INITPINS_LED7_G_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[5] = ((PORTD->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD7 (pin 100) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_LED6_B_PORT, BOARD_INITPINS_LED6_B_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTE24 (pin 31) is configured as PTE24 */
    PORT_SetPinMux(BOARD_INITPINS_LED10_B_PORT, BOARD_INITPINS_LED10_B_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[24] = ((PORTE->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTE25 (pin 32) is configured as PTE25 */
    PORT_SetPinMux(BOARD_INITPINS_LED10_G_PORT, BOARD_INITPINS_LED10_G_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[25] = ((PORTE->PCR[25] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTE26 (pin 33) is configured as PTE26 */
    PORT_SetPinMux(BOARD_INITPINS_LED6_R_PORT, BOARD_INITPINS_LED6_R_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[26] = ((PORTE->PCR[26] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if
                       * pin is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
